### ISSUE TITLE
Nicht Openjdk 21 kompaitbel

### ISSUE THREAD

**Issue by hupling** [it-at-m/itm-java-codeformat#26]
> Caused by: java.lang.NoSuchMethodError: 'com.sun.tools.javac.tree.JCTree com.sun.tools.javac.tree.JCTree$JCImport.getQualifiedIdentifier()

**Comment by devtobi** [comment]
Mir ist nicht ganz klar, was das mit dem Template hier zu tun hat. Schließlich handelt es sich ja nur um eine .xml-Datei. Wenn es mit Java 21 nicht funktioniert, ist es doch wohl eher ein Problem des spotless-maven-plugin, oder?

**Comment by devtobi** [comment]
Bei mir hat es mit JDK 21 wunderbar geklappt. Man muss nur andere relevante Abhängigkeiten mit heben (checkstyle, spotless-maven-plugin, usw.)

**Comment by devtobi** [comment]
Issue kann aus meiner Sicht geschlossen werden. In https://github.com/it-at-m/refarch-templates haben wir eine funktionierende Variante. (Mit aktuell noch veraltetem Spotless-Plugin)
